# Generated by Django 3.0.5 on 2020-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('enrollment', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=70)),
                ('branch', models.CharField(max_length=90)),
                ('year', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=30)),
                ('categeory', models.CharField(max_length=50)),
                ('seattype', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(db_column='Mobile_Number', max_length=15)),
                ('department', models.CharField(db_column='Department', max_length=200)),
                ('registeration_number', models.CharField(db_column='Registeration_Number', max_length=200)),
                ('email_id', models.CharField(db_column='Email_Id', max_length=200)),
            ],
        ),
    ]
